### PR TITLE
adding printing of WebPage into pdf format and downloading web page & session management enabled 

### PR DESCRIPTION
**Pull request by pavannayak321**
adding functionality of following 
1->downloading the web page 

2-> printing the  full web page in pdf format 

3->session managment enabled to store cookies

### CODE REVIEW

**Comment by goxr3plus** [comment]
WOW that's beautiful, i will check your code and accept it if everything works nice :)

**Comment by pavannayak321** [comment]
Glad to hear ...Thank you

**Comment by pavannayak321** [comment]
If any bugs occurs intimate me  so that I can try to solve .. Currently in
working on other functionalities so it can  remove the errors dependencies

**Comment by goxr3plus** [comment]
Great great, now JavaFX it's going solo without Oracle.

**Comment by pavannayak321** [comment]
Ha yup!!!!

**Comment by goxr3plus** [comment]
GREEEATTT :)

**Comment by goxr3plus** [comment]
@pavannayak321  I merged the pull request and did big changed today on this project please check the read me .... on the code i added completely new UI etc .

Please don't change package declaration names from goxr3plus to other .....

Feel free to fork and continue this awesome changes .... 

From now on it complies from Java 10 and above .... we need to add modularization for Java 11 etc

[Check here the latest release :](https://github.com/goxr3plus/JavaFX-Web-Browser/releases/download/V10.0.0/JavaFXWebBrowser-10.0.0.zip)

**Comment by goxr3plus** [comment]
@pavannayak321  I can't get it working with https://jitpack.io/#goxr3plus/JavaFX-Web-Browser Jitpack and Java 10 i don't know why damnn.... i can't release the new version until it's fixed ...

**Comment by pavannayak321** [comment]
Okay

**Comment by goxr3plus** [comment]
You did a very great work by the way :)  I just opened the field and functionality more so you can continue your amazing work if you want. Put Author in the classes wherever you edit :)

**Comment by pavannayak321** [comment]
Okay ...thanks regarding

**Pull request merged**
