### PR TITLE
Source arrangement

### PR DESCRIPTION
**Pull request by evg-tyurin**
* normalize maven source structure: src/main/java is a root of sources
* .classpath includes access rule for javafx/** classes

### CODE REVIEW

**Comment by goxr3plus** [comment]
Hello :). Thank you so much for contributing. I will check the changes.

**Comment by goxr3plus** [comment]
Packages must be all lowercase named ~ https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by goxr3plus** [comment]
@evg-tyurin  Nice work !!

**Comment by evg-tyurin** [comment]
All my commits are automagically connected to the first pull request while I was going to pull only one "Source arrangement" and then consult which part of my work you are interested in.

**Comment by goxr3plus** [comment]
So far I like your code. Only thing I want is to keep package names lowercase. It's Java rule.

**Comment by goxr3plus** [comment]
@evg-tyurin  Beautiful i merged it just now , thank you so much !! :)

Sorry for being late but i am working in other things on parallel :)

**Comment by goxr3plus** [comment]
@evg-tyurin  There is a problem with file : 

[WebBrowserTabController.fxml](https://github.com/goxr3plus/JavaFX-Web-Browser/pull/3/files#diff-08a6820a8e4d4df1558dbd1c05107dcc) 


We should define a custom fxml for this and import it inside Gluon Scene Builder. Gonna fix it .

Gluon Scene Builder Can't Open it:

```
java.io.IOException: javafx.fxml.LoadException: 
/D:/GitHub/JavaFX-Web-Browser/resources/fxml/WebBrowserTabController.fxml

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:98)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:85)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:102)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2540)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:761)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:385)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:665)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:510)
	at com.oracle.javafx.scenebuilder.app.AppPlatform$MessageBoxDelegate.lambda$messageBoxDidGetMessage$0(AppPlatform.java:189)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javafx.fxml.LoadException: 
/D:/GitHub/JavaFX-Web-Browser/resources/fxml/WebBrowserTabController.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2848)
	at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2692)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2661)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2517)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:93)
	... 15 more
Caused by: java.lang.ClassNotFoundException: commons.javafx.webbrowser.browser.SearchEngineComboBox
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2916)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2905)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2846)
	... 20 more

```

**Comment by goxr3plus** [comment]
@evg-tyurin  Just fixed packages . Please don't mess around with them cause i have projects depending on package names . Also i had a hard time configuring again assembly  . 

Just notify me if you want to change something with packages.

Thanks for the pull request anyway :) be happy .

**Pull request merged**
